workspace: beenum22
repo: comet
strategy:
  commits_format:
    type: conventional_commits
    options: null
  development_model:
    type: gitflow
    options:
      stable_branch: master
      development_branch: develop
      release_branch_prefix: release
projects:
- path: .
  version: 0.3.0
  history:
    next_release_type: no_change
    latest_bump_commit_hash: null
  version_regex: ''
  version_files:
  - setup.py
  - src/comet/cli.py
