workspace: beenum22
repo: comet
strategy:
  development_model:
    type: gitflow
    options:
      stable_branch: main
      development_branch: develop
      release_branch_prefix: release
  commits_format:
    type: conventional_commits
    options: {}
projects:
- path: .
  version: 0.0.0
  history:
    next_release_type: ''
    latest_bump_commit_hash: ''
  version_regex: ''
  version_files: []
