strategy: gitflow
workspace: beenum
repo: comet
stable_branch: master
development_branch: develop
release_branch_prefix: release
projects:
- path: .
  stable_version: 0.2.0
  dev_version: 0.2.0
  version_regex: ''
  version_files:
  - setup.py
  - src/comet/cli.py
