#----------------------------------------------------------------------------------------------------------------------#
# Important Notes:
#----------------------------------------------------------------------------------------------------------------------#
#   - Release pipelines should only be executed by the repository administrators
#   - All commits should follow conventional commits specification (https://www.conventionalcommits.org/) if
#     'auto' release option is used
#   - Feature/bugfix branches should be merged to development branch (develop) using squash merge strategy
#   - Hotfix branches should be merged to stable branch (master) using squash merge strategy
#   - Release branches should NOT be merged to stable branch (master) using squash merge strategy
#   - Stable branch should NOT be merged to development branch (develop) using squash merge strategy
#   - Branch permissions should be disabled for stable (master) and development (develop) branches
#----------------------------------------------------------------------------------------------------------------------#
# Required Bitbucket Pipelines Global environment variables
#----------------------------------------------------------------------------------------------------------------------#
# - BITBUCKET_USERNAME
#     Description:
#       Sets Bitbucket username.
#       e.g. muneeb-ahmad
# - BITBUCKET_APP_PASSWORD
#     Description:
#       Sets Bitbucket App password with admin repo privileges.
# - DOCKER_HUB_USERNAME
#     Description:
#       Sets ng-voice Docker registry username.
# - DOCKER_HUB_PASSWORD
#     Description:
#       Sets ng-voice Docker registry password.
# - DOCKER_REGISTRY
#     Description:
#       Sets ng-voice Docker registry.
#       e.g. dockerhub.ng-voice.com
#       Note: DO NOT include protocol URL e.g. 'https://'
# -----
image: atlassian/default-image:2

options:
  docker: true

definitions:
  steps:

    - step: &lint-last-message
        name: Lint Commit Message
        image: gtramontina/commitlint:8.3.5
        script:
          - commitlint --config .commitlint.js --from HEAD~1

    - step: &upgrade-version
        name: Upgrade Version
        image: dockerhub.ng-voice.com/comet:latest
        script:
          - git remote set-url origin https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@bitbucket.org/${BITBUCKET_WORKSPACE}/${BITBUCKET_REPO_SLUG}
          - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          - git fetch origin
          - >-
            comet
            --debug
            --project-version
            --run branch-flow
            --username ${BITBUCKET_USERNAME}
            --password ${BITBUCKET_APP_PASSWORD}
            --connection-type https
        artifacts:
          - .comet.yml

    - step: &build-and-push-comet
        name: Build & Push Comet
        condition:
          changesets:
            includePaths:
              - "src/comet/**"
              - Dockerfile
              - setup.py
              - pyproject.toml
        caches:
          - docker
        script:
          - >-
            if [ -f "shared_vars.sh" ]; then
              source shared_vars.sh
            fi
          - export IMAGE_NAME=dockerhub.ng-voice.com/comet
          - export IMAGE_TAG=$(grep 'dev_version:' .comet.yml | sed 's/^.*: //' | tr + _)
          - echo "${IMAGE_NAME}:${IMAGE_TAG}"
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD dockerhub.ng-voice.com
          - >-
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG}
            -f Dockerfile .
          - docker push ${IMAGE_NAME}:${IMAGE_TAG}
          - >-
            if [[ -v STABLE_BRANCH ]];
              docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
              docker push ${IMAGE_NAME}:latest
            fi

pipelines:
  default:
    - step: *lint-last-message
    - step: *upgrade-version
    - step: *build-and-push-comet

  branches:
    develop:
      - step: *lint-last-message
      - step: *upgrade-version
      - step: *build-and-push-comet