# Available Flow types
#   1. branch_flow
#   2. release
#   3. release_candidate
#   4. sync
# Available Flow functions
#   1. lookup_commits
#   2. version_bump
#   3. merge_branches
#   4. add_branch
#   5. commit_changes
strategy:
  type: gitflow
  #  type: tbd
  #  type: custom
  flows:
    - name: default
      type: branch_flow
      jobs:
        - job: lookup_commits
          parameters:
            reference: develop
            filter_commits: True
            consider_version_history: True
        - job: version_bump
          parameters:
            type: build  # pre_release, build, release
            pre_release_id: dev
            consider_version_history: True
        - commit_changes:
            push: False
      branches:
        - "*/*"
    - name: development
      type: branch_flow
      steps:
        - job: lookup_commits
          parameters:
            reference: stable
            filter_commits: True
            consider_version_history: True
        - job: version_bump
          parameters:
            type: release  # pre_release, build, release
            pre_release_id: dev
            consider_version_history: True
        - job: version_bump
      branches:
        - develop
    - name: release_version
      type: release
      branches:
        - develop
        - release/*
      steps:
        - lookup_commits:
            reference: master
            past_bump_hash_check: False
        - version_bump:
            type: finalize
        - commit_changes
        - merge_branches:
            source: develop
            destination: master
        - add_tags
    - name: release_candidate
      type: release_candidate
      branches:
        - develop
        - release/*
      steps:
        - lookup_commits:
            reference: master
            past_hash_check: False
        - version_bump:
            type: finalize
            update_files: False
        - add_branch:
            name: release/[version]
            checkout: True
        - version_bump:
            type: pre_release
            pre_release_name: rc
            update_files: True
        - commit_changes
    - name: rc
      type: branch_flow
      steps:
        - lookup_commits:
            reference: develop
        - version_bump:
            type: pre_release
            pre_release_id: rc
        - commit_changes:
            push: False
      branches:
        - release/*
workspace: beenum22
repo: mono-repo-new
stable_branch: master
development_branch: develop
release_branch_prefix: release
projects:
  - path: .
    version: 0.0.0+32ccefc
    release_commit_sha: 32ccefc
    version_regex: ''
    version_files: []
