name: Release
on: workflow_dispatch

env:
  GHCR_URL: ghcr.io
  GHCR_IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_IMAGE_NAME: beenum/comet

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Export
        uses: docker/build-push-action@v2
        with:
          context: .
          outputs: type=docker,dest=/tmp/comet.tar
          tags: comet:latest
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: comet-image
          path: /tmp/comet.tar
          retention-days: 1
  release:
    name: Release to Stable Branch
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Git Author
        uses: fregante/setup-git-user@v1
      - name: Setup Python Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Comet
        run: pip install --user .
      - name: Upgrade Version
        run: >-
              comet
              --debug
              release
              --scm-provider github
              --username ${{ secrets.GIT_USERNAME }}
              --password ${{ secrets.GIT_TOKEN }}
              --connection-type https
              --push
      - name: Upload Comet Config
        uses: actions/upload-artifact@v2
        with:
          name: comet-version
          path: .comet.yml
          retention-days: 1
  push-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: comet-image
          path: /tmp
      - uses: actions/download-artifact@v2
        with:
          name: comet-version
      - name: Setup Python Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Comet
        run: pip install --user .
      - name: Set Version Variable
        run: echo "VERSION=$(comet --suppress --project-version . | cut -d' ' -f2 | tr + _)" >> $GITHUB_ENV
      - name: Load Docker Image
        run: |
          docker load --input /tmp/comet.tar
          docker tag comet:latest ${{ env.DOCKERHUB_IMAGE_NAME }}:latest
          docker tag comet:latest ${{ env.GHCR_URL }}/${{ env.GHCR_IMAGE_NAME }}:latest
          docker tag comet:latest ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ env.VERSION }}
          docker tag comet:latest ${{ env.GHCR_URL }}/${{ env.GHCR_IMAGE_NAME }}:${{ env.VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_CR_TOKEN }}
      - name: Extract metadata (tags, labels) for Containers
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: |
            ${{ env.DOCKERHUB_IMAGE_NAME }}
            ${{ env.GHCR_URL }}/${{ env.GHCR_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: Push Container Images
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  sync:
    name: Sync Dev with Stable
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Sync Dev with Stable
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Sync
          token: ${{ secrets.GIT_TOKEN }}
          ref: master