name: Sync
on: workflow_dispatch

jobs:
  sync-with-dev:
    name: Sync Dev with Stable
    runs-on: ubuntu-latest
    needs:
      - upgrade-version
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Git Author
        uses: fregante/setup-git-user@v1
      - name: Setup Python Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Comet
        run: pip install --user .
      - name: Upgrade Version
        run: >-
              comet
              --debug
              --run sync
              --scm-provider github
              --username ${{ secrets.GIT_USERNAME }}
              --password ${{ secrets.GIT_TOKEN }}
              --connection-type https
              --push